### ISSUE TITLE
Alle Modelle in ein einziges Schema packen (1 Schema pro Umgebung)

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-db#1]
Pro Umgebung (live/staging) soll es nur ein Schema geben, es sollen also alle Modelle in ein Schema. Das habe ich bis jetzt noch nicht geschafft. 

Was ich versucht habe:

```
#!/bin/bash

schemas=(oereb oereb_staging)
models="OeREBKRMtrsfr_V1_1;OeREBKRMvs_V1_1;DM01AVSO24LV95;PLZOCH1LV95D"

for schema in ${schemas[@]}; do
  java -jar $ILI2PG_PATH/ili2pg-4.1.0.jar \
  --dbschema ${schema} --models ${models} \
  --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFk --createFkIdx --createEnumTabs --beautifyEnumDispName --createMetaInfo --createUnique --createNumChecks --nameByTopic \
  --createBasketCol --createDatasetCol \
  --createImportTabs --createscript sql/${schema}.sql
done
```

ili2pg meldet hier aber:

```
[...]
Info: lookup model <DM01AVSO24LV95> 2.3 in repository <http://geo.so.ch/models/>
Info: lookup model <DM01AVSO24LV95> 2.3 in repository <http://models.geo.sz.ch/>
Info: lookup model <DM01AVSO24LV95> 2.3 in repository <http://models.geo.ti.ch/>
Info: lookup model <DM01AVSO24LV95> 2.3 in repository <http://models.geo.zg.ch/>
Warning: repository <http://models.geo.zg.ch/> ignored; failed to read ilimodels.xml; javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.; ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
Info: lookup model <DM01AVSO24LV95> 2.3 in repository <http://models.geo.zh.ch/>
Error: DM01AVSO24LV95: model not found
compiler failed
```
Wobei je nach der Reihenfolge, in welcher man vier Modelle auflistet, ein anderes Modell nicht gefunden wird. Ein Bug in einem der ili-Tools?

Andere Variante, die ich versucht habe:

```
#!/bin/bash

schemas=(oereb oereb_staging)
models=(OeREBKRMtrsfr_V1_1 OeREBKRMvs_V1_1 DM01AVSO24LV95 PLZOCH1LV95D)

for schema in ${schemas[@]}; do
  for model in ${models[@]}; do
    java -jar $ILI2PG_PATH/ili2pg-4.1.0.jar \
    --dbschema ${schema} --models ${model} \
    --defaultSrsCode 2056 --strokeArcs --createGeomIdx --createFk --createFkIdx --createEnumTabs --beautifyEnumDispName --createMetaInfo --createUnique --createNumChecks --nameByTopic \
    --createBasketCol --createDatasetCol \
    --createImportTabs --createscript sql/${schema}_${model}.sql
  done
done
```

Problem hier: In jedem der generierten SQL-Skripte steht CREATE SEQUENCE [schemaname].t_ili2db_seq; 
Also wird pro Schema 4 Mal derselbe Befehl ausgeführt, was nicht geht, weil die Sequenz nach dem ersten Aufruf bereits exisitert.

Ideen?

**Comment by schmandr** [comment]
Für den Moment gibt es als Zwischenlösung nun die Schemen

- live_oereb
- live_dm01avso24
- live_plzoch1d
- stage_oereb
- stage_dm01avso24
- stage_plzoch1d

Siehe https://github.com/sogis/oereb-db/commit/3865af3664e3e9a2a6b97438e679781a0e1fd9e3

**Comment by edigonzales** [comment]
Erledigt?

**Comment by schmandr** [comment]
Ist mit https://github.com/sogis/oereb-db/commit/01c0ce245541e4688e4d22e2505e0a6614211455 im Prinzip umgesetzt. Aber ich bin noch nicht ganz glücklich mit

> ATTENTION: You must manually edit the *_ili2.sql scripts and remove the duplicate DDL statements (duplicate to the ili1 script).

Hintergrund ist, dass wir bei der Option `--models` nicht alle Modelle miteinander angeben können, weil einige INTERLIS 1, andere INTERLIS 2.3 sind. Also müssen wir das mit zwei `ili2pg`-Befehlen lösen. Dann ist aber im zweiten SQL-File z.B. nochmal ein` CREATE SEQUENCE live.t_ili2db_seq;` enthalten. Diese Sequenz gibt es aber bereits vom ersten SQL-File her, wie ich das schon oben festgestellt habe. Und das ist noch einer der überblickbareren Fälle. Dieses Verhalten ist wohl eine Restriktion des Features "SQL generieren ohne Verbindung zur DB".

Ich habe mal erarbeitet, wie man das per Skript herausfiltern könnte. Aber man greift so eben in die `ili2db`-Interna ein, die ja auch mal ändern könnten:

```
sed -i -e 's/CREATE SEQUENCE/-- CREATE SEQUENCE/' sql/*_ili2.sql
sed -i -e 's/CREATE TABLE \(.*T_ILI2DB\)/CREATE TABLE IF NOT EXISTS \1/' sql/*_ili2.sql
sed -i -e 's/\(CREATE.*INDEX\) \(T_ILI2DB\)/\1 IF NOT EXISTS \2/' sql/*_ili2.sql
sed -i -e 's/\(ALTER TABLE .*T_ILI2DB.* ADD CONSTRAINT .* FOREIGN KEY\)/-- \1/' sql/*_ili2.sql
sed -i -e 's/\(INSERT INTO .*T_ILI2DB_SETTINGS\)/-- \1/' sql/*_ili2.sql

```

Wären deshalb vielleicht zwei Schemen pro Umgebung (einmal ÖREB-Themen mit INTERLIS 2.3, einmal AV und PLZ mit INTERLIS 1) nicht doch besser? Oder was meinen denn @edigonzales und @claeis  dazu?

**Comment by edigonzales** [comment]
Mir gefällt der 1-Schema-Ansatz immer noch. Vor allem fände ich den Grund warum man zwei Schemen macht komisch (INTERLIS 1 vs INTERLIS 2).

Im Prinzip macht man das Herstellen der SQL-Scripts ja nur einmal und dann werden sie ins Image gebrannt. Wenn der ÖREB-Kataster (als Gesamt-Anwendung) fertig ist, gibt es keinen Grund, dass sich die Skripte "dauernd" ändern.

Aber: Auf die TODO-Liste von ili2pg.

**Comment by schmandr** [comment]
Ist seit https://github.com/sogis/oereb-db/commit/01c0ce245541e4688e4d22e2505e0a6614211455 gelöst. Mit https://github.com/sogis/oereb-db/commit/826e94d95f4a0f2671000e21a1e954ba0a636008 nun auch so, dass nach dem Generieren der Skripts keine Handarbeit mehr nötig ist. Hoffentlich "verheben" die sed-Befehle.
