### ISSUE TITLE
Refresh der materialisierten Views

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#12]
Kann nur der Owner. Ist der jetzige Owner der richtige?

**Comment by andreasneumann** [comment]
@schmandr - was ist deine Meinung hier?

Im Moment ist "admin" der Owner der materialisierten Views. Sollte das geändert werden?

ogc_server hat "SELECT"-Rechte

**Comment by schmandr** [comment]
Wir müssen wohl den User _gretl_ zum Owner machen, weil er die Daten importieren wird. Weil die Benutzernamen aber per Env-Variable konfiguriert werden können soll und weil beim Anlegen der Views der User noch nicht existiert, können wir das nicht in _create_oereb-wms_views.sh_ machen, sondern erst später. Müssen wir anschauen.

**Comment by schmandr** [comment]
Ich habe eine mögliche Lösung erarbeitet: https://github.com/sogis/oereb-db/commit/1051c0bfa7745fb99dfc9949d2de93bea219c1a2. Sie ist allerdings nicht dynamisch, d.h. wenn neue materialisierte Views hinzukommen, muss man dran denken, die Befehle in der Datei pgconf/grants.sql zu ergänzen.

Während der Erarbeitung von Lösungen habe ich mir überlegt, ob es nicht besser wäre, statt der materialisierten Views Tabellen anzulegen, die mit GRETL aktualisiert werden. Dann würde sich das Ändern des Owners zu gretl erübrigen. Dies zu ändern würde aber wohl recht viel Aufwand für @andreasneumann bedeuten.

Was ist eure Meinung dazu? Ist meine jetztige Lösung OK, oder muss sie dynamisch funktionieren?

**Comment by schmandr** [comment]
SQL-Befehl, um die `ALTER TABLE` statements zu generieren:

```sql
SELECT
  concat_ws(' ', 'ALTER TABLE', concat_ws('.', nspname, relname), 'OWNER TO :PG_WRITE_USER;')
FROM
  pg_class
JOIN
  pg_namespace
    ON pg_class.relnamespace = pg_namespace.oid
WHERE
  nspname IN ('stage', 'live')
  AND
  relname LIKE 'vw_oerebwms_%'
ORDER BY
  nspname, relname
;
```

Wenn man ihn mit `psql  --quiet --tuples-only ...` ausführt, kriegt man ihn ohne dekorierendes "Beigemüse".

**Comment by schmandr** [comment]
Wir belassen es bei dieser Lösung, da nicht ständig neue materialisierte Views hinzukommen.
