### ISSUE TITLE
Indizes in ÖREB-DB

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#13]
@schmandr hat das angesprochen. Muss man im Auge behalten. Z.B. falls Refreshen der materialisierten Views lange dauert. Da sind Indizes bei den Dokumenten und den Eigentumsbeschränkungen (z.B. Thema/Subthema) Kandidaten.

**Comment by andreasneumann** [comment]
Ja - auch auf den materialized Views selber sollten Indizes gemacht werden, insbesondere räumliche.

Ein Thema das sicher aktuell wird, sobald mehrere Gemeinden importiert wurden.

Nur bei einer Gemeinde merkt man das wohl kaum.

**Comment by andreasneumann** [comment]
Indizes an materialized views hinzugefügt: https://github.com/sogis/oereb-db/commit/bf0b991ecf333714bcb8e5408d53c2b616bd123a

@schmandr - kümmerst Du dich um die Indizes an den normalen Tabellen? Das gehört ja irgendwie auch zur Datenstruktur der leeren DB.

**Comment by edigonzales** [comment]
Stand? Materialized Views gibt es ja nicht mehr? Schliessen?

**Comment by andreasneumann** [comment]
Ich habe die wesentlichen Tabellen (dokumente, hinweisweiteredokumentem eigentumsbeschraenkungen und deren geometrien) geprüft. Alle notwendigen Indizes für das Abfüllen der Daten sind vorhanden.

Auch die neu erstellten Tabellen für den ÖREB-WMS haben die notwendigen Indizes (artcode und geometrien).

Materialized views gibt es nicht mehr, aber der oereb-wms braucht views wegen der json-Einschränkung in QGIS Server 2.x
