### ISSUE TITLE
Use gretl-runtime Docker image instead of building a new image for testing

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-db#16]
https://github.com/sogis/oereb-db/blob/1910947252c663ca3afae02f7dbd15b1e77ebf68/docker-compose.test.yml#L6

**Comment by edigonzales** [comment]
Stand?

**Comment by schmandr** [comment]
Ist vorbereitet in Branch https://github.com/sogis/oereb-db/tree/use_gretl_image und funktioniert nun auch, seit ich von dir erfahren habe, dass ich `/usr/pgsql-10/bin/pg_isready` aufrufen muss statt nur `pg_isready`. Werde ich heute noch mergen.
