### ISSUE TITLE
Travis errors

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#2]
see travis logs

**Comment by edigonzales** [comment]
Der Build läuft trotz der Fehler durch. Problem hier ist, dass der GRETL-Job im Container läuft und Travis so nicht weiss, ob der GRETL-Job erfolgreich war oder nicht. Man sieht es bloss auf der Konsole.

**Comment by schmandr** [comment]
Hierfür habe ich eigentlich die Zeile https://github.com/sogis/oereb-db/blob/9fd371681af7f3412cec98fb64a5bfe09ed164c3/.travis.yml#L17 eingebaut. Die printet bei Fehler im GRETL-Job zwar brav "1", ihr tatsächlicher Exit-Code ist aber offenbar dennoch "0"... Anschauen, wie das funktionieren sollte.
