### ISSUE TITLE
Materialized Views ersetzen durch Tabelle

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#20]
Die materialisierten Views sollen durch Tabellen ersetzt werden.

**Comment by edigonzales** [comment]
Untergegangen ist, dass wir konsequenterweise für diese Tabellen ein "ÖREB-Publikationsmodell" machen sollten. 

Das kann aber nachträglich gemacht werden, resp. soll das Herstellen eines lauffähigen Zustandes momentan nicht hindern.

**Comment by andreasneumann** [comment]
Umgesetzt in oereb-db commits b9e21058c424d9911422d34e955917f125c0c420, 83d6248a511bf6c14c12ba3da2d64a8c2286fc05 und e5f1eeac0eec1ba8264746cf712dad5c9bc20a98
sowie in div. oereb-wms und oereb-gretljobs commits. Wir am Freitag, 25.10. in der Test- und/oder Integrationsumgebung von @schmandr ausgerollt.
