### ISSUE TITLE
DB as a service

### ISSUE THREAD

**Issue by giodegiorgi** [sogis/oereb-db#23]
Dear all,

are you using DB as a service in a Kubernetes infra?
Great job.

Cheers
G.

**Comment by edigonzales** [comment]
Ciao Giovanni

no, we wanted to but were running out of time (1) so we decided to use our vm-based databases and the docker image for testing and showcase purposes. The generated SQL will be used for the production databases.

(1) We have no experiences with databases in a openshift/kubernetes cluster.
Stefan

**Comment by giodegiorgi** [comment]
Ciao Stefan,

thanks, for the info, how about the docker-compose connection to the vm instances? 

Regards
Gio

**Comment by edigonzales** [comment]
Ciao Giovanni

what do you mean with "connection to the vm instances"?

Stefan

**Comment by leader80** [comment]
Hi Stefan,

I wanted to know how you access the containers from other containers, via link?

Cheers
Giovanni

**Comment by edigonzales** [comment]
Take a look at this docker-compose file: 
https://gitlab.com/sogis/oereb-kataster/oereb-stack/blob/master/docker-compose.yml#L3
https://gitlab.com/sogis/oereb-kataster/oereb-stack/blob/master/docker-compose.yml#L58

The oereb-web-service container uses the service name of the database container for the jdbc connection url: jdbc:postgresql://db:5432/oereb

regards
Stefan
