### ISSUE TITLE
Health check in Dockerfile

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#26]
Spricht etwas gegen: 

```
HEALTHCHECK --interval=30s --timeout=30s --start-period=60s CMD /usr/pgsql-11/bin/pg_isready -h localhost -p 5432
```

Wobei mir die drei Optionen nicht ganz klar sind...

**Comment by schmandr** [comment]
Vorschlag (bin mir aber auch nicht ganz sicher):

`--interval=30s --timeout=5s --start-period=60s`

* timeout kürzer, weil _pg_isready_ meiner Erfahrung nach i.d.R. wirklich "sofort" eine Antwort kriegt
* start-period könnte man vielleicht auch ganz weglassen (d.h. dann default 0s), weil die DB zumindest im Moment nach ca. 20s schon parat ist

**Comment by edigonzales** [comment]
done https://github.com/sogis/oereb-db/commit/e8413cd24ee278d0f666de243d3b190482288880
