### ISSUE TITLE
Warum gibt es Views?

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#27]
Braucht es die Views zum Casten des `dokumente`-Attribut?

Was ist der Stand in QGIS-Server? Funktioniert das mit 3.10?

**Comment by andreasneumann** [comment]
Ja - das ist wegen der Abwärtskompatibilität der Dokumente (json als text) mit QGIS Server 2.x. Das hat @Luescher so gewünscht, soviel ich weiss, damit man gewisse Daten auch im allgemeinen Web-GIS (Web-GIS Client) primär für Prüfungszwecke darstellen kann.

@Luescher - bitte kommentieren, falls ich das falsch in Erinnerung habe.

Wenn wir später alles auf QGIS Server 3.x umgestellt haben, dann können die Views abgeschafft werden.

**Comment by Luescher** [comment]
Das stimmt so. Im AGDI sind für die Views Dataset erfasst. Wenn das Attribut "Dokument" json ist erkennt er die Wert nicht. Das klappt momentan nur wenn es eben Text ist. 

Siehe https://git.sourcepole.ch/ktso/somap/issues/512
