### ISSUE TITLE
Warum gibt es Bundes-KbS-Tabellen und Views?

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#28]
Brauchen wir die für irgend etwas?

**Comment by edigonzales** [comment]
Falls man die nicht braucht, müssen sie auch im KbS-Gretl-Job im update.sql gelöscht werden.

**Comment by andreasneumann** [comment]
Entfernung der Tabellen/Views in oereb-db: https://github.com/sogis/oereb-db/commit/a056eb56a8b1cf6c1c58623d1745a935ea95b62c

Entfernung der Updates der Bundes-KBS-Themen:
https://github.com/sogis/oereb-gretljobs/commit/92bd4260406c9a1f511e3ff5e00bdff70ee064cb
