### ISSUE TITLE
Encoding-Fehler beim Erstellen der Datenbank

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#3]
```
postgres_1  | ERROR:  current transaction is aborted, commands ignored
until end of transaction block
postgres_1  | ERROR:  invalid byte sequence for encoding "UTF8": 0xfc
postgres_1  | ERROR:  invalid byte sequence for encoding "UTF8": 0xe4 0x6e 0x6b
postgres_1  | ERROR:  invalid byte sequence for encoding "UTF8": 0xe4 0x6e 0x6b
postgres_1  | ERROR:  invalid byte sequence for encoding "UTF8": 0xd6 0x52
postgres_1  | ERROR:  current transaction is aborted, commands ignored
until end of transaction block
```

Ich _glaube_ vor https://github.com/sogis/oereb-db/commit/1d9f307580491bdfabfb81db810ad0305a1b0e5c hat es funktioniert.

Ich habe jetzt wieder `iconv -f iso-8859-1 -t utf-8 < setup.sql > setup.sql.new` ausgeführt. `git diff`sieht dann gemäss Screenshot aus.

![Screenshot 2019-07-06 at 18 37 56](https://user-images.githubusercontent.com/2767800/60758971-e9e36380-a01d-11e9-9e85-123d6c3e39b2.png)

**Comment by edigonzales** [comment]
Wenn man in https://github.com/sogis/oereb-db/commit/1d9f307580491bdfabfb81db810ad0305a1b0e5c sich das Diff von `setup.sql` anschaut, sieht man, dass die "Fragezeichen im Diamant" wieder eingeführt werden.

**Comment by schmandr** [comment]
Ich kann mir nicht ganz erklären, was hier passiert ist. Ist vielleicht ein Problem, das nur auf der Maschine von @claeis auftritt.

Um es zu vermeiden, wäre denkbar, das Generieren der SQL-Skripte ebenfalls auf Travis durchzuführen. Das wäre vielleicht recht elegant, ist aber m.E. nicht vordringend.
