### ISSUE TITLE
Modell OeREB_ExtractAnnex_V1_0 aus INTERLIS-Repo beziehen statt von lokal

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-db#6]
Ich bräuchte das Modell _OeREB_ExtractAnnex_V1_0_, damit ich am ili2pg-Skript Verbesserungen machen kann.

**Comment by edigonzales** [comment]
Sollte bei Andrea erhältlich sein. Ich kann es - falls i.O. - in unser Repos schmeissen.

**Comment by schmandr** [comment]
Ich kann nicht beurteilen, ob es i.O. ist. Habe es deshalb vorübergehend hier ins Repo eingecheckt. Sobald es im INTERLIS-Repo ist, nehm' ich es wieder raus. Und entferne die Zeile https://github.com/sogis/oereb-db/blob/5d4d8de7818ec1ffab037be587ab36f336de96ab/create_schema_sql_scripts.sh#L15.

**Comment by edigonzales** [comment]
Habs in das Repo deployed. Da wir ja jetzt automatisch das Repo auch scharf deployen, können wir auch mögliche Änderungen schnell reagieren. Denke, man kann es hier jetzt löschen.

**Comment by schmandr** [comment]
Erledigt mit https://github.com/sogis/oereb-db/commit/c1c002920f9501a3de686c2becc3ac5fc463cddd
