### ISSUE TITLE
[WMS-Views] Attribut "aussage" ist leer

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-db#9]
Man muss sich für eines der "lokalisierten" Attribute entscheiden. In unserem Fall "aussage_de". Das Attribut in der View würde ich bis auf weiteres immer noch "aussage" benennen und nicht "aussage_de".

https://github.com/sogis/oereb-db/blob/master/sql/oereb-wms-views.sql#L14 etc. pp.

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-db/commit/91d2553eae14b8df0774f226e34419b50c2dfc5a
